version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: bash -c "alembic upgrade head  && uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
  
  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
    env_file:
      - ./backend/.env
    ports:
      - 6379:6379
    command:
      - "--save 10 100"
      - "--requirepass password"

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    

volumes:
    postgres_data:
    redis-data:
    redisinsight:
